### ISSUE TITLE
Document the configuration

### ISSUE THREAD

**Issue by gajus** [gajus/prepack-webpack-plugin#1]
The official repository does not provide documentation for the Node.js interface.

https://github.com/facebook/prepack

However, we can see the options with description in the CLI interface.

https://github.com/facebook/prepack/blob/57cc59c07d164e4827c24637af9c1002b0c4a3c8/src/prepack-cli.js#L81-L87

**Comment by tejasbubane** [comment]
Seems like those options are documented here: https://prepack.io/getting-started.html

**Comment by gajus** [comment]
Thank you
