### ISSUE TITLE
[Question] Is it possibile to apply prepack with this plugin over the js transpiled by typescript?

### ISSUE THREAD

**Issue by Ks89** [gajus/prepack-webpack-plugin#10]
Probably it is a stupid question, but is "Is it possibile to apply prepack with this plugin over the js transpiled by typescript?".
But it should be also: "Would this be useful?".

Did you try to apply this plugin on an angular (>=2) application written in Typescript?

Thank u,
Ks89

**Comment by gajus** [comment]
> Probably it is a stupid question, but is "Is it possibile to apply prepack with this plugin over the js transpiled by typescript?".

Sure.

> But it should be also: "Would this be useful?".

That depends the goals. Read about prepacks goals see if they align with you are wanting to achieve.

**Comment by phts** [comment]
> Sure.

@gajus Could you please provide an example how to achieve this?
