### ISSUE TITLE
Plugin interferes with UglifyJsPlugin

### ISSUE THREAD

**Issue by fruchtose** [gajus/prepack-webpack-plugin#11]
This plugin is awesome! Thanks for writing this. There is one small issue I've found: it undoes the minification performed by `webpack.optimize.UglifyJsPlugin`, adding indentation and formatting. It would be great if this plugin could be run in the Webpack compile cycle prior to the Uglify plugin.

**Comment by yocontra** [comment]
@fruchtose Why not run it before uglifying? I don't think you'll get any benefit doing it after uglification, if anything it will probably be worse at identifying blocks to simplify on minified code

**Comment by fruchtose** [comment]
Ah, you're right. I had misconfigured my plugins list. Thanks!

**Comment by nifgraup** [comment]
Perhaps the README should include an example with Uglify?

**Comment by wx-chevalier** [comment]
yes, it's better to include an example with Uglify in README. When i ignore the order, i am surprised to find that bundle even bigger
