### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version ">=6.1.0 <7.0.0".

### ISSUE THREAD

**Issue by FateRiddle** [gajus/prepack-webpack-plugin#13]
If I want to use this plugin, do I have to use node version between 6.1.0 - 7.0.0?
The lastest version is 7.10.0 and I love those es6 supports provided in the latest versions.

**Comment by joshmanders** [comment]
I'm not entirely sure what the flag is on npm, but with yarn you can do `--ignore-engines` and yarn will install and not care about the engine.

**Comment by FateRiddle** [comment]
Cool, it works now for a small demo I wrote with a simple entry of index.js containing one immediate invoke function. Bundle.js now contains only one line of code.

But put it into recent React project, nothing happens. Bundle file size doesn't change.

What I add to `webpack.config.js` is: 

`const PrepackPlugin = require('prepack-webpack-plugin').default`
...
and then in `plugins` array, add `new PrepackPlugin()`

other plugins used are `UglifyJsPlugin` and `CommonsChunkPlugin`. @joshmanders

**Comment by joshmanders** [comment]
@FateRiddle 

That problem I do not know, I have not used prepack nor this plugin yet, I was just reading issues and saw yours and knew the answer. :)

**Comment by gajus** [comment]
https://github.com/gajus/prepack-webpack-plugin/issues/7
