### ISSUE TITLE
Add support for source maps.

### ISSUE THREAD

**Issue by gajus** [gajus/prepack-webpack-plugin#2]
The current implementation does generate the sourcemaps.

https://github.com/gajus/prepack-webpack-plugin/blob/f49be023de806007b0fb428d8294963b7b18ff5b/src/index.js#L36

**Comment by montogeek** [comment]
This mean pass our sourcemaps to `prepack` through the plugin?

**Comment by gajus** [comment]
@montogeek I am already doing this just in case. :-)

**Comment by gajus** [comment]
https://github.com/gajus/prepack-webpack-plugin/commit/c34f8037a2bbc3ec224046ec6b76cd1cd60f0a32
