### ISSUE TITLE
Support `webpack@3`

### ISSUE THREAD

**Issue by alexander-akait** [gajus/prepack-webpack-plugin#29]
:+1:

**Comment by gajus** [comment]
Does this require code change or is it only about updating package.json?

**Comment by alexander-akait** [comment]
@gajus seems only `package.json`

**Comment by gajus** [comment]
Done

**Comment by alexander-akait** [comment]
@gajus can you publish release?

**Comment by gajus** [comment]
It is published by the CI job.
