### ISSUE TITLE
prepack-webpack-plugin v2.0.0 (git-tag + npm release)

### ISSUE THREAD

**Issue by denji** [gajus/prepack-webpack-plugin#46]
```
yarn add -D gajus/prepack-webpack-plugin#40f437b
yarn add -D gajus/prepack-webpack-plugin#master
```

WebPack v4.x: `Error: Cannot find module 'prepack-webpack-plugin'`

https://github.com/gajus/prepack-webpack-plugin/commit/40f437be63488243a0de304c6b6b36dd9b23c4e9

**Comment by denji** [comment]
@gajus This code is not suitable for the dev version stub https://github.com/gajus/prepack-webpack-plugin/blob/9941433/package.json#L47

**Comment by gajus** [comment]
It is not suitable for what?
