### ISSUE TITLE
Doesn't work with node 7

### ISSUE THREAD

**Issue by hanford** [gajus/prepack-webpack-plugin#7]
the `engine` line in the `package.json` prevents people from being able to install on node versions greater than 7

**Comment by TheLarkInn** [comment]
Should probably set the Engine to match for this plugin so experience is consistent

**Comment by gajus** [comment]
> the engine line in the package.json prevents people from being able to install on node versions greater than 7

In what way? it is set to `"node": ">6.0.0"`.

**Comment by tejasbubane** [comment]
@hanford Are you referring to [package.json of prepack itself](https://github.com/facebook/prepack/blob/master/package.json#L84)?

`yarn` did not let me install `prepack` with nodejs `v7.3.0`. But I could install via `npm`. There is a [PR](https://github.com/facebook/prepack/pull/509) to upgrade node version.

**Comment by xzilja** [comment]
👍 Ran into same situation, able to install via npm, but not yarn

**Comment by gajus** [comment]
This is an "issue" with prepack, not with prepack-webpack-plugin.

**Comment by hanford** [comment]
Ahh that could have been the case.

Thanks for the quick responses!

**Comment by brunolemos** [comment]
@gajus they have updated it to "node": ">=6.1.0 <8.0.0"
